### ISSUE TITLE
How to correctly import styles?

### ISSUE THREAD

**Issue by cobbdan** [aws/mynah-ui#342]
## System details

- OS:
- Enviroment to run:
    - [X] Web
    - [ ] VSCode Amazon Q Chat
    - [ ] JetBrains IntelliJ Amazon Q Chat

## Question

I downloaded the light and dark themes from the theme builder (https://aws.github.io/mynah-ui/) and loaded them in my page, but there seems to be some styles that are missing. Is there another stylesheet I need somewhere? It looks like there are a bunch of extra styles coming from "styles.scss" that aren't in the theme files.

There are lots of little things missing, but here's one example:

#### Style cascade from the live demo:
![Image](https://github.com/user-attachments/assets/22ede752-0c09-4564-bef5-cae0b0a8d8d2)

#### Style cascade from my page:
![Image](https://github.com/user-attachments/assets/09141dad-60e1-4dab-9d58-dc9e58774da5)

**Comment by cobbdan** [comment]
An update on this, @avi-alpert was able to track down how other projects are getting the missing style rules and they are including the following rules manually:
```css
                body,
                html {
                    background-color: var(--mynah-color-bg);
                    color: var(--mynah-color-text-default);
                    height: 100%;
                    width: 100%;
                    overflow: hidden;
                    margin: 0;
                    padding: 0;
                }
```

I'm not entirely sure how they knew to do that, but are these missing styles a bug?
